
BUILD_FLAGS = -W -Wall -pedantic 
CC = g++
RM = rm
OUT = *.out

all:  abbytan_assignment1.out

abbytan_assignment1.out: Makefile abbytan_assignment1.cpp
	$(CC) $(BUILD_FLAGS) -o abbytan_assignment1.out abbytan_assignment1.cpp
	
clean:
	$(RM) $(OUT)


